src/accs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('detail/<int:pk>/', views.ProfileDetail.as_view(), name='profile_detail'),
    path('update/<int:pk>/', views.ProfileUpdate.as_view(), name='profile_update'),
]

src/cart/urls.py
from django.urls import path

from . import views
app_name = "cart"
urlpatterns = [
    path('add-to-cart/', views.CartDetail.as_view(), name='add-to-cart'),
    path('recalculate-cart/', views.RecalculateCart.as_view(), name='recalculate-cart'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from accs import urls as accs_urls
from cart import urls as cart_urls
from order import urls as order_urls

from groups import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home_page_list'),

    path('slovary', views.slovary, name='slovary'),

    path('admin/', admin.site.urls),
    path('accs/', include(accs_urls)),
    path('cart/', include(cart_urls, namespace="cart")),
    path('order/', include(order_urls, namespace="order")),

    path('authors/', views.AuthorsList.as_view(), name='authors_list'),
    path('authors/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
    path('author-delete/<int:pk>/', views.AuthorDelete.as_view(), name='author_delete'),
    path('author-update/<int:pk>/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author-create/', views.AuthorCreate.as_view(), name='author_create'),

    path('genres/', views.GenresList.as_view(), name='genres_list'),
    path('genres-create/', views.GenresCreate.as_view(), name='genres_create'),
    path('genress/<int:pk>/', views.GenresDetail.as_view(), name='genres_detail'),
    path('genres-delete/<int:pk>/', views.GenresDelete.as_view(), name='genres_delete'),
    path('genres-update/<int:pk>/', views.GenresUpdate.as_view(), name='genres_update'),

    path('publishing_house/', views.PHList.as_view(), name='publishing_house_list'),
    path('publishing_house-create/', views.PHCreate.as_view(), name='publishing_house_create'),
    path('publishing_houses/<int:pk>/', views.PHDetail.as_view(), name='publishing_house_detail'),
    path('publishing_house-delete/<int:pk>/', views.PHDelete.as_view(), name='publishing_house_delete'),
    path('publishing_house-update/<int:pk>/', views.PHUpdate.as_view(), name='publishing_house_update'),

    path('series/', views.SeriesList.as_view(), name='series_list'),
    path('series-create/', views.SeriesCreate.as_view(), name='series_create'),
    path('seriess/<int:pk>/', views.SeriesDetail.as_view(), name='series_detail'),
    path('series-delete/<int:pk>/', views.SeriesDelete.as_view(), name='series_delete'),
    path('series-update/<int:pk>/', views.SeriesUpdate.as_view(), name='series_update'),

    path('book/', views.BookList.as_view(), name='book_list'),
    path('book-create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('book-delete/<int:pk>/', views.BookDelete.as_view(), name='book_delete'),
    path('book-update/<int:pk>/', views.BookUpdate.as_view(), name='book_update'),
]

src/groups/models.py
from django.conf import settings
from django.db import models
import datetime

# Create your models here.


class Authors(models.Model):
    author_name = models.CharField("Имя автора", max_length=50)
    author_description = models.TextField("Краткая биография", null = True, blank = True) 
    author_img = models.ImageField(
        upload_to = 'images',
        null = True, 
        blank = True
        ) 

    def __str__(self):
        return self.author_name

class Genres(models.Model):
    genres_name = models.CharField("Жанр", max_length=50)
    genres_description = models.TextField("Описание", null = True, blank = True)

    def __str__(self):
        return self.genres_name

class Publishing_house(models.Model):
    publishing_house_name = models.CharField("Издательство", max_length=50)
    publishing_house_description = models.TextField("Описание", null = True, blank = True)

    def __str__(self):
        return self.publishing_house_name

class Series(models.Model):
    series_name = models.CharField("Серия", max_length=50)
    series_description = models.TextField("Описание", null = True, blank = True)
    
    def __str__(self):
        return self.series_name

class Book(models.Model):
    book_name = models.CharField("Название", max_length=50)
    book_desc = models.TextField("Описание", null = True, blank = True)
    book_auth = models.ForeignKey(Authors, verbose_name="Автор", on_delete = models.PROTECT)
    book_genre = models.ForeignKey(Genres, verbose_name="Жанр", on_delete = models.PROTECT)
    book_ph = models.ForeignKey(Publishing_house, verbose_name="Издательство", on_delete = models.PROTECT, null = True, blank = True)
    book_sery = models.ForeignKey(Series, verbose_name="Серия", on_delete = models.PROTECT, null = True, blank = True)
    book_add = models.DateTimeField(
        verbose_name="Время добавления",
        auto_now=False,
        auto_now_add=True
    )
    book_img = models.ImageField(
        upload_to = 'images',
        null = True, 
        blank = True
        )
    price = models.DecimalField(
        verbose_name="Цена/бел.руб",
        default=0,
        max_digits=5,
        decimal_places=2
    )

src/groups/forms.py
from django import forms
from django.db.models import fields
from . import models

class SearchForm(forms.Form):
    query = forms.CharField(label="")
    fields = forms.CharField(widget=forms.HiddenInput)
    direction = forms.CharField(widget=forms.HiddenInput)  

src/groups/views.py
from django.shortcuts import render
from django.http import HttpResponse
from groups.models import Authors
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from .models import Authors, Genres, Publishing_house, Series, Book
from groups import models as ref_models
from . import forms
from django.db.models import Q


# Create your views here.


class HomePage(ListView):
    model = Book
    template_name ='groups/homepage_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["books"] = ref_models.Book.objects.all().order_by("-pk")[:5]
        context["authors"] = ref_models.Authors.objects.all().order_by("-pk")[:5]
        return context
    
    

#Страница со словарями
def slovary(request):
    context = {}
    return render(request, template_name="slovary.html", context=context)



#АВТОРЫ
class AuthorsList(ListView):
    model = Authors

class AuthorUpdate(UpdateView):
    model = Authors
    success_url = "/authors/"
    fields = ('author_img','author_name', 'author_description')
    template_name_suffix = '_update'

class AuthorCreate(CreateView):
    model = Authors
    success_url = "/authors/"
    fields = ('author_img','author_name', 'author_description')

class AuthorDetail(DetailView):
    model = Authors

class AuthorDelete(DeleteView):
    success_url = "/authors/"
    model = Authors



#ЖАНРЫ
class GenresList(ListView):
    model = Genres

class GenresCreate(CreateView):
    model = Genres
    success_url = "/genres/"
    fields = ('genres_name', 'genres_description')
    template_name_field = 'genres'

class GenresDetail(DetailView):
    model = Genres

class GenresDelete(DeleteView):
    success_url = "/genres/"
    model = Genres

class GenresUpdate(UpdateView):
    model = Genres
    success_url = "/genres/"
    fields = ('genres_name', 'genres_description')
    template_name_suffix = '_update'



#Издательства
class PHList(ListView):
    model = Publishing_house

class PHCreate(CreateView):
    model = Publishing_house
    success_url = "/publishing_house/"
    fields = ('publishing_house_name', 'publishing_house_description')
    template_name_field = 'publishing_house'

class PHDetail(DetailView):
    model = Publishing_house

class PHDelete(DeleteView):
    success_url = "/publishing_house/"
    model = Publishing_house

class PHUpdate(UpdateView):
    model = Publishing_house
    success_url = "/publishing_house/"
    fields = ('publishing_house_name', 'publishing_house_description')
    template_name_suffix = '_update'



#СЕРИИ
class SeriesList(ListView):
    model = Series

class SeriesCreate(CreateView):
    model = Series
    success_url = "/series/"
    fields = ('series_name', 'series_description')
    template_name_field = 'series'

class SeriesDetail(DetailView):
    model = Series

class SeriesDelete(DeleteView):
    success_url = "/series/"
    model = Series

class SeriesUpdate(UpdateView):
    model = Series
    success_url = "/series/"
    fields = ('series_name', 'series_description')
    template_name_suffix = '_update'



#КНИГИ
class BookList(ListView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        field_sort = self.request.GET.get('field')
        direction_sort = self.request.GET.get('direction')
        context["field_sort"] = field_sort
        context["direction_sort"] = direction_sort
        query = self.request.GET.get('query')
        context["search_form"] = forms.SearchForm(initial={
            "query":query,
            "field":field_sort,
            "direction":direction_sort
            })
        return context

    def get_ordering(self):
        ordering_by = 'pk'
        field_sort = self.request.GET.get('field')
        direction_sort = self.request.GET.get('direction')
        if field_sort and direction_sort:
            if direction_sort == 'up':
                direction = ""
            else:
                direction = "-"
            ordering_by = f'{direction}{field_sort}'
        return ordering_by
    
    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('query')
        if q:
            print(q)
            qs = qs.filter(Q(book_name__contains=q))
        return qs
    
    

class BookCreate(CreateView):
    model = Book
    success_url = "/book/"
    fields = (
        'book_img',
        'book_name',
        'book_desc',
        'book_genre',  
        'book_auth',
        'book_ph',
        'book_sery',
        'price'
    )
    template_name_field = 'book'

class BookDetail(DetailView):
    model = Book

class BookDelete(DeleteView):
    success_url = "/book/"
    model = Book

class BookUpdate(UpdateView):
    model = Book
    success_url = "/book/"
    fields = (
        'book_img',
        'book_name',
        'book_desc',
        'book_genre',  
        'book_auth',
        'book_ph',
        'book_sery',
        'price'
    )
    template_name_suffix = '_update'

src/groups/templates/groups/authors_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Редактирование</title>
{% endblock title %}

{% block main %}
    <main class="px-3">
        <h1>Удаление автора {{object.author_name}}!!!</h1>
        <form action="" method='POST'>
         {% csrf_token %}
         <button class="btn btn-danger">Вы уверены?</button>
    </main>
 {% endblock main %}

src/groups/templates/groups/authors_detail.html
{% extends 'base.html' %}
{% load ref_tags %}

{% block title %}
    <title>{{object.author_name}}</title>
{% endblock title %}

{% block main %}
<main class="px-3" align="left">
  <img src={% auth_img_safe object.pk%} alt="Обложка" style="width:140; height:220">}
  <h2>
    Имя Автора: {{object.author_name}}
  </h2>
  <h3>{{object.author_description|default:'No description'}}</h3><br>
  <br>
  {% if user.is_staff %}
  <a class="btn btn-light" href='{% url 'authors_list' %}'>Вернуться к списку авторов</a>
  {% else %}
  <a class="btn btn-light" href='{% url 'home_page_list' %}'>Вернуться к домашней странице</a>
  {% endif %}
 </body>
</main>
{% endblock main %}

src/groups/templates/groups/authors_form.html
{% extends 'base.html' %}

{% block title %}
    <title>Добавить Автора</title>
{% endblock title %}>


 {% block main %}
    <main class="px-3">
    <h1>Добавить Автора</h1>
    <form action="" method='POST'>
        {% csrf_token %}
        <table class="table table-dark table-hover table-bordered"> 
        {{ form.as_ul }} <br>
        </table> 
        <button class="btn btn-light">Добавить!</button>
    </main>
 {% endblock main %}

src/groups/templates/groups/book_detail.html
{% extends 'base.html' %}
{% load ref_tags %}

{% block title %}
    <title>{{object.book_name}}</title>
{% endblock title %}

{% block main %}
<main class="px-3" align="left">
  <h2>
    Книга: {{object.book_name}}
  </h2>
  <img src={% book_img_safe book.pk%} alt="Обложка" style="width:140; height:220">
  <h3>{{object.book_desc|default:'No description'}}</h3><br>
  Жанр: {{object.book_genre|default:'No genre'}}<br>
  Серия: {{object.book_sery|default:'No sery'}}<br>
  Автор: {{object.book_auth|default:'No author'}}<br>
  Издательство: {{object.book_ph|default:'No publishing house'}}<br>
  Дата добавления в магазин: {{object.book_add}}<br>
  <br>
  <a class="btn btn-light" href='{% url 'book_list' %}'>Вернуться к списку книг</a>
 </body>
</main>
{% endblock main %}

src/groups/templates/groups/book_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Добавить Книгу</title>
{% endblock title %}>


 {% block main %}
    <main class="px-3">
    <h1>Добавить Книгу</h1>
    <form enctype=multipart/form-data action="" method='POST' class = "uniForm" >
        {% csrf_token %}
        <table class="table table-dark table-hover table-bordered"> 
        {{ form|crispy }} <br>
        </table> 
        <button class="btn btn-light">Добавить!</button>
    </main>
 {% endblock main %}

src/groups/templates/groups/book_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load ref_tags %}


{% block title %}
    <title>Все книги</title>
{% endblock title %}


{% block main %}
<main class="px-3">
    <h1>Все книги:<h1>
    <form action="{{current_url}}" method="GET">
        поиск: {{search_form|crispy}}
        <input type="hidden" name="field" value="{{field_sort}}">
        <input type="hidden" name="direction" value="direction_sort">
    </form>
    <table class="table table-dark table-hover table-bordered">
        <tr>
            <td><a href="?field=pk&direction={% if field_sort == 'pk' and direction_sort == 'up'%}down{% else %}up{% endif %}">№
            {% if field_sort == 'pk' and direction_sort == 'up'%}
            <i class="fas fa-angle-up"></i>
            {% elif field_sort == 'pk' and direction_sort == 'down'%}
            <i class="fas fa-angle-down"></i>
            {% else %}
            {% endif %}
            <a></td>
            <td>Обложка</td>
            <td><a href="?field=book_name&direction={% if field_sort == 'book_name' and direction_sort == 'up'%}down{% else %}up{% endif %}">Название
            {% if field_sort == 'book_name' and direction_sort == 'up'%}
            <i class="fas fa-angle-up"></i>
            {% elif field_sort == 'book_name' and direction_sort == 'down'%}
            <i class="fas fa-angle-down"></i>
            {% else %}
            {% endif %}
            <a></td>
            <td>Описание</td>
            <td><a href="?field=book_auth&direction={% if field_sort == 'book_auth' and direction_sort == 'up'%}down{% else %}up{% endif %}">Автор
            {% if field_sort == 'book_auth' and direction_sort == 'up'%}
            <i class="fas fa-angle-up"></i>
            {% elif field_sort == 'book_auth' and direction_sort == 'down'%}
            <i class="fas fa-angle-down"></i>
            {% else %}
            {% endif %}
            <a></td>
            <td>Цена</td>
            <td>Действия</td>
        </tr>
        {% for book in object_list%}
           <tr>
                <td>{{book.pk}}</td>
                <td><img src={% book_img_safe book.pk%} alt="Обложка" style="width:140; height:220"></td>
                <td><a href={% url 'book_detail' book.pk%}>{{book.book_name}}</a></td>
                <td>{{book.book_desc}}</td>
                <td>{{book.book_auth}}</td>
                <td>{{book.price}}</td>
                {% if user.is_staff %}
                <td>
                    <a href={% url 'book_delete' book.pk%}><i class="far fa-trash-alt"></i></a>
                    <a href={% url 'book_update' book.pk%}><i class="fas fa-pen"></i></a>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:add-to-cart' %}?book={{book.pk}}"><i class="fas fa-cart-arrow-down"></i></a>
                </td>
                {% endif %}
           </tr>
        {% endfor %}
    </table>
   <div class="d-grid gap-2">
    {% if user.is_staff %}
    <a class="btn btn-light" href={% url 'book_create'%} role="button">Добавить книгу</a>
    {% else %}
    <a class="btn btn-light" href='{% url 'home_page_list' %}'>Вернуться к домашней странице</a>
    {% endif %}
   </div>
  </main>
{% endblock main %}
  

src/groups/templates/groups/genres_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Удаление</title>
{% endblock title %}

{% block main %}
    <main class="px-3">
        <h1>Удаление жанра: {{object.genres_name}}!!!</h1>
        <form action="" method='POST'>
         {% csrf_token %}
         <button class="btn btn-danger">Вы уверены?</button>
    </main>
 {% endblock main %}

src/groups/templates/groups/genres_form.html
{% extends 'base.html' %}

{% block title %}
    <title>Добавить Жанр</title>
{% endblock title %}>


 {% block main %}
    <main class="px-3">
    <h1>Добавить Жанр</h1>
    <form action="" method='POST'>
        {% csrf_token %}
        <table class="table table-dark table-hover table-bordered"> 
        {{ form.as_ul }} <br>
        </table> 
        <button class="btn btn-light">Добавить!</button>
    </main>
 {% endblock main %}

src/groups/templates/groups/genres_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Все жанры</title>
{% endblock title %}
    

{% block main %}
<main class="px-3">
    <h1>Все жанры:<h1>
    <table class="table table-dark table-hover table-bordered">
        <tr>
            <td>#</td>
            <td>Жанр</td>
            <td>Описание</td>
            <td>Действия</td>
        </tr>
        {% for genre in object_list%}
           <tr>
                <td>{{genre.pk}}</td>
                <td><a href={% url 'genres_detail' genre.pk%}>{{genre.genres_name}}</a></td>
                <td>{{genre.genres_description}}</td>
                <td>
                    <a href={% url 'genres_delete' genre.pk%}>Delete</a>
                    <a href={% url 'genres_update' genre.pk%}>Update</a>
                </td>
           </tr>
        {% endfor %}
    </table>
   <div class="d-grid gap-2">
   <a class="btn btn-light" href={% url 'genres_create'%} role="button">Добавить жанр</a>
   </div>
  </main>
{% endblock main %}
  

src/groups/templates/groups/homepage_list.html
{% extends 'base.html' %}
{% load static %}
{% load ref_tags %}

{% block title %}
    <title>AllBooks</title>
{% endblock title %}

{% block home %}
active
{% endblock home %}
   

{% block main %}
<br>
<main class="px-3">
<h1>AllBooks - Твоё решение для покупки книги!<h1><br>
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" style="margin-bottom:18px">
      <div class="row g-0">
        <img src="{% static '/groups/img/img2.jpg' %}" class="d-block w-100" alt="..." style="max-width: 440px; margin-left:85px; height:220">
      </div>
    </div>
{% for book in books%}
    <div class="carousel-item">
      <div class="card mb-3" style="max-width: 440px; margin-left:85px">
        <div class="row g-0">
          <div class="col-md-4">
            <img src={% book_img_safe book.pk%} alt="Обложка" style="width:140; height:220">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title" style="color:black">{{book.book_name}}</h5>
              <p class="card-text" style="color:black">{{book.book_desc}}</p>
              <a class="btn btn-light" href="{% url 'cart:add-to-cart' %}?book={{book.pk}}">Добавить в карзину</a>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endfor %}
  </div>
    
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Предыдущий</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Следующий</span>
  </button>
</div>
<a class="btn btn-light" href='{% url 'book_list' %}'>Список всех книг</a
<br>
<h1>Новые авторы</h1>
<div id="carouselExampleControls2" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" style="margin-bottom:18px">
      <div class="row g-0">
        <img src="{% static '/groups/img/auth.jpg' %}" class="d-block w-100" alt="..." style="max-width: 440px; margin-left:85px; height:220">
      </div>
    </div>
{% for auth in authors%}
    <div class="carousel-item">
      <div class="card mb-3" style="max-width: 440px; margin-left:85px">
        <div class="row g-0">
          <div class="col-md-4">
            <img src={% auth_img_safe auth.pk%} alt="Обложка" style="width:140; height:220">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title" style="color:black">{{auth.author_name}}</h5>
              <p class="card-text" style="color:black">{{auth.author_description}}</p>
              <a class="btn btn-light" href="/authors/{{auth.pk}}" >об авторе</a>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endfor %}
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls2"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Предыдущий</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls2"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Следующий</span>
  </button>
</div>
</main>
{% endblock main %}

src/groups/templates/groups/publishing_house_detail.html
{% extends 'base.html' %}

{% block title %}
    <title>{{object.publishing_house_name}}</title>
{% endblock title %}

{% block main %}
<main class="px-3" align="left">
  <h2>
    Издательство: {{object.publishing_house_name}}
  </h2>
  <h3>{{object.publishing_house_description|default:'No description'}}</h3><br>
  <br>
  <a class="btn btn-light" href='{% url 'publishing_house_list' %}'>Вернуться к списку издательств</a>
 </body>
</main>
{% endblock main %}

src/groups/templates/groups/publishing_house_form.html
{% extends 'base.html' %}

{% block title %}
    <title>Добавить Издательство</title>
{% endblock title %}>


 {% block main %}
    <main class="px-3">
    <h1>Добавить Издательство</h1>
    <form action="" method='POST'>
        {% csrf_token %}
        <table class="table table-dark table-hover table-bordered"> 
        {{ form.as_ul }} <br>
        </table> 
        <button class="btn btn-light">Добавить!</button>
    </main>
 {% endblock main %}

src/groups/templates/groups/series_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Удаление</title>
{% endblock title %}

{% block main %}
    <main class="px-3">
        <h1>Удаление серии: {{object.series_name}}!!!</h1>
        <form action="" method='POST'>
         {% csrf_token %}
         <button class="btn btn-danger">Вы уверены?</button>
    </main>
 {% endblock main %}

src/groups/templates/groups/series_form.html
{% extends 'base.html' %}

{% block title %}
    <title>Добавить Серию</title>
{% endblock title %}>


 {% block main %}
    <main class="px-3">
    <h1>Добавить Серию</h1>
    <form action="" method='POST'>
        {% csrf_token %}
        <table class="table table-dark table-hover table-bordered"> 
        {{ form.as_ul }} <br>
        </table> 
        <button class="btn btn-light">Добавить!</button>
    </main>
 {% endblock main %}